# Basic Information 
title: Xinjing-Guo
position: Ph.D. Student
affiliation: School of Microelectronics, Fudan University
affiliation_link: https://sme.fudan.edu.cn
affiliation2: Key Laboratory of Computational Physical Sciences (MOE), Fudan University
affiliation_link2: https://phys.fudan.edu.cn
affiliation_logo: ./assets/img/LogoWhite.jpg
email: xinjingguo22@m.fudan.edu.cn

# Search Engine Optimization (SEO)
keywords: xinjing guo, xinjing-guo, guo xinjing, xinjing, guoxinjing
canonical: https://xinjing-guo.github.io/
description: Xinjing-Guo(郭新敬) now is a Phd student at Fudan University. His research lies in 
# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=un7c83MAAAAJ
cv_link: ./assets/Resume of XinjingGuo.pdf
github_link: https://github.com/Xinjing-Guo
#linkedin: https://www.linkedin.com/in/liuyaoyao/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar:  ./assets/img/IMG_0546.jpeg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to contact me!
footnote_link: https://xinjing-guo.github.io

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
